=== jelinj8/Java-BSToolbox/src/main/resources/META-INF/XmlFilesystem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://bliksoft.cz/XmlFilesystem"
	xmlns="http://bliksoft.cz/XmlFilesystem" elementFormDefault="qualified">
	<xs:element name="root">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="file" />
				<xs:element ref="require" />
				<xs:element ref="include" />
				<xs:element ref="classpath" />
				<xs:element ref="attribute" />
				<xs:element ref="symlink" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="file">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="symlink" />
				<xs:element ref="file" />
				<xs:element ref="attribute" />
				<xs:element ref="require" />
				<xs:element ref="include" />
				<xs:element ref="classpath" />
			</xs:choice>

			<xs:attribute name="name" type="xs:string"
				use="required" />
			<xs:attribute name="position" type="xs:integer" />
			<xs:attribute name="type" type="xs:string" />
			<xs:attribute name="id" type="xs:string" />
			<xs:attribute name="target" type="xs:string" />
			<xs:attribute name="sorted" type="xs:boolean" />
			<xs:attribute name="remove" type="xs:boolean" />
			<xs:attribute name="replace" type="xs:boolean" />
			<xs:attribute name="locked" type="xs:boolean" />
			<xs:attribute name="translation" type="xs:string" />
			<xs:attribute name="mark" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string"
						use="required" />
					<xs:attribute name="value" type="xs:string" />
					<xs:attribute name="translation" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="require">
		<xs:complexType>
			<xs:attribute name="path" type="xs:string"
				use="required" />
			<xs:attribute name="mode" default="ro">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ro" />
						<xs:enumeration value="rw" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="include">
		<xs:complexType>
			<xs:attribute name="path" type="xs:string"
				use="required" />
			<xs:attribute name="mode" default="ro">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ro" />
						<xs:enumeration value="rw" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="classpath">
		<xs:complexType>
			<xs:attribute name="path" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="symlink">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="path" type="xs:string" />
			<xs:attribute name="target-id" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jelinj8/Java-BSToolbox/src/main/resources/cz/bliksoft/javautils/xmlfilesystem/FilesystemModule.xml
<root xmlns="http://bliksoft.cz/XmlFilesystem"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://bliksoft.cz/XmlFilesystem https://bliksoft.cz/schemas/XmlFilesystem.xsd">

	<file name="fileLoaders">
		<file
			name="cz.bliksoft.javautils.xmlfilesystem.loaders.ClassFileLoader" />
	</file>

	<!-- self-credit for the About dialog of common-java-utils-jfx (lib_credits, see its
	     doc/Help.md; same id as its own entry, so the two merge; LGPL21 is defined there) -->
	<file name="lib_credits" sorted="true">
		<file name="bstoolbox">
			<attribute name="name" value="BSToolbox (common-java-utils)" />
			<attribute name="url" value="https://github.com/jelinj8/Java-BSToolbox" />
			<attribute name="comment" value="application framework core: modules, XmlFilesystem, utilities" />
			<attribute name="licence" value="LGPL21" />
		</file>
	</file>
</root>
